### PR TITLE
resolves #19, resolves #18

### LINKED ISSUE #18: Add pagination for results

### LINKED ISSUE #19: Ability to set limit on number of results returned
and set a hardcoded default limit

### PR DESCRIPTION
**Pull request by tylerswayne**

### CODE REVIEW

**Comment by waldoj** [comment]
Does this make it possible for somebody to retrieve results _without_ pagination? If somebody wants 1000 results in one go, I don't see any reason not to allow that.

**Comment by tylerswayne** [comment]
Before, elastic by default was only returning 10 results (or less if your query produced less than 10).  With this change you can get as many as you want and start at whatever index.  The 'start' variable defaults to 0, so you would just add &limit=1000 or however many you want and you get the first 1000.

**Comment by waldoj** [comment]
Er. Oh. Yes. Right.

I am not a smart man.

**Comment by waldoj** [comment]
:shipit:

**Pull request merged**
